### PR TITLE
Updated games.md to make speaker names bold

### PR DESCRIPTION
**Pull request by Crammers**
changed speaker names to be bold in games.md

### CODE REVIEW

**Review by hzoo — APPROVED** [review]
Ah looks like you did 2 actually! Not an issue though

**Comment by hzoo** [comment]
Thanks, above and beyond haha!

**Comment by hzoo** [comment]
Oh and if it's interesting give the podcast a listen 😛

**Comment by Crammers** [comment]
> Ah looks like you did 2 actually! Not an issue though

Oh no sorry, I didn't realise I pushed that to GitHub, I was going to do that if no one else picked it up. 
Yeah reading it made me want to check it out, so I will! Cheers 😄

**Pull request merged**
